import type { ApiGameCategory } from '~/types/game'

const PUBLIC_GAME_CATALOG: ApiGameCategory[] = [
  {
    id: 'arcade',
    key: 'arcade',
    nameKey: 'gameCatalog.category.arcade.name',
    descriptionKey: 'gameCatalog.category.arcade.description',
    img: '/images/games/categories/arcade.webp',
    icon: 'mdi-rocket-launch-outline',
    subCategories: [
      {
        id: 'reflex',
        key: 'reflex',
        nameKey: 'gameCatalog.subCategory.reflex.name',
        descriptionKey: 'gameCatalog.subCategory.reflex.description',
        img: '/images/games/subcategories/reflex.webp',
        icon: 'mdi-lightning-bolt-outline',
        games: [
          {
            id: 'flappy-rocket',
            key: 'flappy-rocket',
            nameKey: 'gameCatalog.games.flappyRocket.name',
            descriptionKey: 'gameCatalog.games.flappyRocket.description',
            img: '/images/games/flappy-rocket.webp',
            icon: 'mdi-rocket-outline',
            component: 'flappy-rocket',
            supportedModes: ['ai'],
            developmentStatus: 'playable',
          },
        ],
      },
      {
        id: 'cards',
        key: 'cards',
        nameKey: 'gameCatalog.subCategory.cards.name',
        descriptionKey: 'gameCatalog.subCategory.cards.description',
        img: '/images/games/subcategories/cards.webp',
        icon: 'mdi-cards-outline',
        games: [
          {
            id: 'solitaire',
            key: 'solitaire',
            nameKey: 'gameCatalog.games.solitaire.name',
            descriptionKey: 'gameCatalog.games.solitaire.description',
            img: '/images/games/solitaire.webp',
            icon: 'mdi-cards-playing-outline',
            component: 'solitaire',
            supportedModes: ['ai'],
            developmentStatus: 'playable',
            mood: 'chill',
            visualStyle: 'classic',
            averageDuration: '8 min',
          },
          {
            id: 'hearts',
            key: 'hearts',
            nameKey: 'gameCatalog.games.hearts.name',
            descriptionKey: 'gameCatalog.games.hearts.description',
            img: '/images/games/hearts.webp',
            icon: 'mdi-cards-heart-outline',
            component: 'hearts',
            supportedModes: ['ai'],
            developmentStatus: 'playable',
            mood: 'strategy',
            visualStyle: 'classic',
            averageDuration: '15 min',
          },
          {
            id: 'spades',
            key: 'spades',
            nameKey: 'gameCatalog.games.spades.name',
            descriptionKey: 'gameCatalog.games.spades.description',
            img: '/images/games/spades.webp',
            icon: 'mdi-cards-spade-outline',
            component: 'spades',
            supportedModes: ['ai'],
            developmentStatus: 'playable',
            mood: 'competitive',
            visualStyle: 'classic',
            averageDuration: '18 min',
          },
          {
            id: 'ludo',
            key: 'ludo',
            nameKey: 'gameCatalog.games.ludo.name',
            descriptionKey: 'gameCatalog.games.ludo.description',
            img: '/images/games/ludo.webp',
            icon: 'mdi-dice-multiple-outline',
            component: 'ludo',
            supportedModes: ['pvp'],
            developmentStatus: 'coming_soon',
            mood: 'chill',
            visualStyle: 'classic',
            averageDuration: '20 min',
          },
        ],
      },
    ],
  },
]

export default defineEventHandler(() => PUBLIC_GAME_CATALOG)
